import java.io.File

String pipeline_name
pipelineJob('eric-enm-int-pm-kube-state-metrics-prepare') {
    description ('prepare microservice PM KUBE STATE METRICS integration chart - autogenerated using JobDSL - all manual changes will be overwritten!')
    concurrentBuild(allowConcurrentBuild = false)
    logRotator {
        numToKeep(30)
    }
    parameters {
        stringParam('CHART_NAME')
        stringParam('CHART_REPO')
        stringParam('CHART_VERSION')
        labelParam('SLAVE') {
            defaultValue("${SLAVE}")
            description('')
        }
    }

    definition {
        cpsScm {
            scm {
                git {
                    branch('master')
                    remote {
                        credentials('lciadm100_private_key')
                        url("ssh://gerrit-gamma.gic.ericsson.se:29418/OSS/ENM-Parent/SQ-Gate/com.ericsson.oss.containerisation/eric-enm-int-pm-kube-state-metrics")
                    }
                    extensions {
                         cleanBeforeCheckout()
                    }
                }
            }
            scriptPath("jenkins/prepare.jenkinsfile")
            lightweight(lightweight = true)
        }
    }
}

pipelineJob('eric-enm-int-pm-kube-state-metrics-test') {
    description ('Test microservice PM KUBE STATE METRICS integration chart - autogenerated using JobDSL - all manual changes will be overwritten!')
    concurrentBuild(allowConcurrentBuild = false)
    logRotator {
        numToKeep(30)
    }
    parameters {
        stringParam('INT_CHART_VERSION')
        stringParam('INT_CHART_REPO')
        stringParam('NAMESPACE')
        labelParam('SLAVE') {
            defaultValue("${SLAVE}")
            description('')
        }
    }

    definition {
        cpsScm {
            scm {
                git {
                    branch('master')
                    remote {
                        credentials('lciadm100_private_key')
                        url("ssh://gerrit-gamma.gic.ericsson.se:29418/OSS/ENM-Parent/SQ-Gate/com.ericsson.oss.containerisation/eric-enm-int-pm-kube-state-metrics")
                    }
                    extensions {
                         cleanBeforeCheckout()
                    }
                }
            }
            scriptPath("jenkins/test.jenkinsfile")
            lightweight(lightweight = true)
        }
    }
}


pipelineJob('eric-enm-int-pm-kube-state-metrics-publish') {
    description ('publish microservice PM KUBE STATE METRICS integration chart - autogenerated using JobDSL - all manual changes will be overwritten!')
    concurrentBuild(allowConcurrentBuild = false)
    logRotator {
        numToKeep(30)
    }
    parameters {
        stringParam('CHART_NAME')
        stringParam('CHART_REPO')
        stringParam('CHART_VERSION')
        labelParam('SLAVE') {
            defaultValue("${SLAVE}")
            description('')
        }
    }

    definition {
        cpsScm {
            scm {
                git {
                    branch('master')
                    remote {
                        credentials('lciadm100_private_key')
                        url("ssh://gerrit-gamma.gic.ericsson.se:29418/OSS/ENM-Parent/SQ-Gate/com.ericsson.oss.containerisation/eric-enm-int-pm-kube-state-metrics")
                    }
                    extensions {
                         cleanBeforeCheckout()
                    }
                }
            }
            scriptPath("jenkins/publish.jenkinsfile")
            lightweight(lightweight = true)
        }
    }
}

pipelineJob('Spinnaker_ENM_APP_STAGING_PM_KUBE_STATE_METRICS_Updater') {
    description ('This job is used to update the ENM App Staging-1 of PM KUBE STATE METRICS Service - autogenerated using JobDSL - all manual changes will be overwritten!')
    concurrentBuild(allowConcurrentBuild = false)
    logRotator {
        numToKeep(30)
    }
    parameters {
        stringParam('spinnaker_application_name')
        stringParam('spinnaker_pipeline_name')
        stringParam('spinnaker_fem_controller')
        labelParam('SLAVE') {
            defaultValue("${SLAVE}")
            description('')
        }
    }

    definition {
        cpsScm {
            scm {
                git {
                    branch('master')
                    remote {
                        credentials('lciadm100_private_key')
                        url("ssh://gerrit-gamma.gic.ericsson.se:29418/OSS/ENM-Parent/SQ-Gate/com.ericsson.oss.containerisation/eric-enm-int-pm-kube-state-metrics")
                    }
                    extensions {
                         cleanBeforeCheckout()
                    }
                }
            }
            scriptPath("jenkins/spinnaker.jenkinsfile")
            lightweight(lightweight = true)
        }
    }
}

